# Generated by Django 5.0.3 on 2024-04-12 11:44

import django.core.validators
import django.db.models.deletion
import employees.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Наименование')),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='positions', to='auth.group', verbose_name='Роль')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_superuser', models.BooleanField(default=False, help_text='Определяет, является ли данный пользователь суперпользователем.', verbose_name='Статус суперпользователя')),
                ('username', models.CharField(error_messages={'unique': 'Пользователь с таким именем уже зарегистрирован'}, max_length=16, unique=True, validators=[django.core.validators.MinLengthValidator(3), employees.validators.UsernameValidator()], verbose_name='Имя пользователя')),
                ('password', models.CharField(max_length=128, verbose_name='Пароль')),
                ('FIO', models.CharField(max_length=100, verbose_name='ФИО')),
                ('salary', models.PositiveIntegerField(verbose_name='Зарплата')),
                ('address', models.CharField(max_length=64, verbose_name='Адрес')),
                ('phone_number', models.CharField(max_length=10, verbose_name='Номер телефона')),
                ('is_staff', models.BooleanField(default=False, help_text='Определяет, является ли данный пользователь членом персонала', verbose_name='Статус персонала')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный пользователь')),
                ('registered', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Последний вход')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='Права пользователя')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='employees.position', verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='Год')),
                ('month', models.PositiveIntegerField(verbose_name='Месяц')),
                ('procurements', models.PositiveIntegerField(verbose_name='Количество закупок')),
                ('productions', models.PositiveIntegerField(verbose_name='Количество производств')),
                ('sales', models.PositiveIntegerField(verbose_name='Количество продаж')),
                ('common', models.PositiveIntegerField(verbose_name='Общее количество участий')),
                ('bonus', models.FloatField(verbose_name='Бонус')),
                ('general', models.PositiveIntegerField(verbose_name='К выдаче')),
                ('is_issued', models.BooleanField(default=False, verbose_name='Выдано')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salaries', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Зарплата',
                'unique_together': {('year', 'month', 'employee')},
            },
        ),
    ]
