# Generated by Django 5.0.1 on 2024-01-21 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='Год')),
                ('month', models.PositiveIntegerField(verbose_name='Месяц')),
                ('procurements', models.PositiveIntegerField(verbose_name='Количество закупок')),
                ('productions', models.PositiveIntegerField(verbose_name='Количество производств')),
                ('sales', models.PositiveIntegerField(verbose_name='Количество продаж')),
                ('common', models.PositiveIntegerField(verbose_name='Общее количество участий')),
                ('bonus', models.PositiveIntegerField(verbose_name='Бонус')),
                ('general', models.PositiveIntegerField(verbose_name='К выдаче')),
                ('is_issued', models.BooleanField(default=False, verbose_name='Выдано')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salaries', to='employees.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Зарплата',
                'unique_together': {('year', 'month', 'employee')},
            },
        ),
    ]
