# Generated by Django 5.0.1 on 2024-02-11 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='bonus',
            field=models.FloatField(verbose_name='Бонус'),
        ),
    ]
