# Generated by Django 5.0.1 on 2024-01-17 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Procurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(verbose_name='Количество')),
                ('sum', models.FloatField(verbose_name='Сумма')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procurements', to='employees.employee', verbose_name='Сотрудник')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procurements', to='materials.material', verbose_name='Сырье')),
            ],
            options={
                'verbose_name': 'Закупка',
                'verbose_name_plural': 'Закупки',
            },
        ),
    ]
