# Generated by Django 5.0.3 on 2024-04-12 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materials', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(verbose_name='Количество')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingredients', to='materials.material', verbose_name='Сырье')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingredients', to='products.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Интредиент',
                'verbose_name_plural': 'Ингредиенты',
                'unique_together': {('product', 'material')},
            },
        ),
    ]
