# Generated by Django 5.0.3 on 2024-04-12 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(verbose_name='Количество')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productions', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productions', to='products.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Производство',
            },
        ),
    ]
