# Generated by Django 5.0.3 on 2024-03-30 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='Сумма')),
                ('term', models.PositiveSmallIntegerField(verbose_name='Срок')),
                ('annual_percent', models.PositiveIntegerField(default=20, verbose_name='Процент годовых')),
                ('penalties', models.PositiveIntegerField(default=2, verbose_name='Пени')),
                ('date', models.DateField(verbose_name='Дата получения')),
            ],
            options={
                'verbose_name': 'Кредит',
                'verbose_name_plural': 'Кредиты',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('amount', models.FloatField(verbose_name='Основная сумма')),
                ('percent', models.FloatField(verbose_name='Процент')),
                ('general_amount', models.FloatField(verbose_name='Общая сумма')),
                ('days_overdue', models.PositiveIntegerField(verbose_name='Просрочено дней')),
                ('penalties', models.FloatField(verbose_name='Пени')),
                ('total', models.FloatField(verbose_name='Итого')),
                ('remains', models.FloatField(verbose_name='Остаток')),
                ('credit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='bank.credit', verbose_name='Кредит')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
            },
        ),
    ]
